
services:
  hmzrt-backend:
    build: .
    container_name: hmzrt-backend
    ports:
      - "81:81"
      - "443:443"
    volumes:
      - ./certs:/app/certs:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:81
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/api.hmzrt.eu_full.pfx
    networks:
      - hmzrt-network
    restart: unless-stopped
    healthcheck: 
      test: ["CMD", "curl", "-kf", "https://localhost:443/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  hmzrt-network:
    driver: bridge
